version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ops_portal_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ops_portal
      # Uncomment below for production with authentication
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: your_secure_password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - ops_portal_network

  mongo-express:
    image: mongo-express:latest
    container_name: ops_portal_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      # Uncomment below if MongoDB has authentication
      # ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: your_secure_password
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: your_secure_password
    depends_on:
      - mongodb
    networks:
      - ops_portal_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  ops_portal_network:
    driver: bridge